trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - feature/*

variables:
  TF_VERSION: "1.9.0"

stages:
# ---------------------- PR VALIDATION STAGE ----------------------
- stage: PR_Validation
  displayName: "Pull Request Validation"
  condition: eq(variables['Build.Reason'], 'PullRequest')
  jobs:
    - job: terraform_validate
      displayName: "Terraform Validate + Security Scan"
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: UseAzureCLI@1
          inputs:
            version: latest

        - script: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install terraform
            terraform -v
          displayName: "Install Terraform"

        - script: |
            terraform fmt -check
          displayName: "Check Terraform Formatting"

        - script: |
            terraform init
            terraform validate
          displayName: "Terraform Validate"

        - script: |
            echo "Running Trivy IaC Scan..."
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -
            trivy config --severity HIGH,CRITICAL .
          displayName: "Security Scan (Trivy)"

# ---------------------- DEPLOYMENT STAGE ----------------------
- stage: Deploy
  displayName: "Terraform Apply to Azure"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  jobs:
    - deployment: terraform_apply
      environment: production
      displayName: "Terraform Apply"
      pool:
        vmImage: ubuntu-latest
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureCLI@2
                inputs:
                  azureSubscription: "Your-Service-Connection"
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    terraform init
                    terraform plan -out tfplan
                    terraform apply -auto-approve tfplan
