pool:
  name: 'todoapp'

trigger: none

variables:
  - group: common_variables
  - name: backendAzureRmKey
    value: '${{ parameters.environment }}.tfstate'
  - name: work_dir
    value: "$(System.DefaultWorkingDirectory)/environments/${{ parameters.environment }}"

parameters:
  - name: environment
    displayName: "Which Environment You want to Build?"
    type: string
    values: 
    - dev
    - prod

  - name: scanning
    displayName: "Run Terraform Scanning?"
    type: boolean
    default: false
    values: 
    - true
    - false
  
  - name: plan
    displayName: "Run Terraform plan?"
    type: boolean
    default: false
    values: 
    - true
    - false

  - name: approval
    displayName: "Manual apprvoal?"
    type: boolean
    default: false
    values: 
    - true
    - false

  - name: apply
    displayName: "Run Terraform Apply?"
    type: boolean
    default: false
    values: 
    - true
    - false

stages:
# ======================================================
# STAGE 1 — OPTIONAL: PRE-COMMIT SCANNING
# ======================================================
- stage: PreCommit
  displayName: "Pre-Commit / Static Analysis"
  jobs:

    # --------------------------------------------------
    # Job 1 - Validate
    # --------------------------------------------------
    - job: TerraformValidate
      displayName: "Terraform Validate"
      continueOnError: true
      condition: eq(${{ parameters.scanning}}, 'true')
      steps:
        - task: CmdLine@2
          displayName: "Check Terraform Path"
          inputs:
            script: |
              export PATH=$PATH:/usr/local/bin
              terraform version

        - task: TerraformTask@5
          inputs:
            provider: azurerm
            command: init
            workingDirectory: '$(work_dir)'
            backendServiceArm: '$(service_connection)'
            backendAzureRmStorageAccountName: '$(stg_account_name)'
            backendAzureRmContainerName: tfstate
            backendAzureRmKey: '$(backendAzureRmKey)'

        - task: TerraformTask@5
          inputs:
            provider: azurerm
            command: validate
            workingDirectory: '$(work_dir)'


    # --------------------------------------------------
    # Job 2 - Format
    # --------------------------------------------------
    - job: TerraformFmt
      displayName: "Terraform FMT"
      continueOnError: true
      condition: eq(${{ parameters.scanning}}, 'true')
      steps:
        - task: TerraformTask@5
          inputs:
            provider: azurerm
            command: custom
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            customCommand: 'fmt -check'
            outputTo: console
            environmentServiceNameAzureRM: '$(service_connection)'


    # --------------------------------------------------
    # Job 3 - tfsec
    # --------------------------------------------------
    - job: TfsecScan
      displayName: "tfsec Security Scan"
      continueOnError: true
      condition: eq(${{ parameters.scanning}}, 'true')
      dependsOn: TerraformFmt
      steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)'


    # --------------------------------------------------
    # Job 4 - TFLint
    # --------------------------------------------------
    - job: TFLintScan
      displayName: "TFLint Scan"
      continueOnError: true
      condition: eq(${{ parameters.scanning}}, 'true')
      dependsOn: TfsecScan
      steps:
        - task: Bash@3
          inputs:
            targetType: inline
            script: |
              tflint --init
              tflint --recursive -f compact
            workingDirectory: '$(work_dir)'
# ======================================================
# STAGE 2 — COST ESTIMATION
# ======================================================
# - stage: CostStage
#   displayName: "Cost & Impact Assessment"
#   dependsOn: PreCommit
#   jobs:
#     - job: InfraCost
#       displayName: "Infracost Breakdown"
#       steps:
#       - task: PowerShell@2
#         inputs:
#           targetType: inline
#           script: 'infracost breakdown --path=.'
#           workingDirectory: '$(work_dir)'


# ======================================================
# STAGE 2 — PLAN (ALWAYS RUN)
# ======================================================
- stage: Plan
  displayName: "Terraform Plan"
  jobs:
    - job: TerraformPlan
      displayName: "Terraform Plan Execution"
      continueOnError: true
      condition: eq(${{ parameters.plan}}, 'true')
      steps:
        - task: TerraformTask@5
          inputs:
            provider: azurerm
            command: init
            workingDirectory: '$(work_dir)'
            backendServiceArm: '$(service_connection)'
            backendAzureRmStorageAccountName: '$(stg_account_name)'
            backendAzureRmContainerName: tfstate
            backendAzureRmKey: '$(backendAzureRmKey)'

        - task: TerraformTask@5
          inputs:
            provider: azurerm
            command: plan
            workingDirectory: '$(work_dir)'
            environmentServiceNameAzureRM: '$(service_connection)'



# ======================================================
# STAGE 3 — APPROVAL
# ======================================================
- stage: Approval
  displayName: "Manual Approval"
  dependsOn: Plan
  condition: succeeded()      # Runs only when plan succeeded
  jobs:
    - job: ManualApproval
      pool: server
      steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'jeet.bhatrai@hotmail.com'



# ======================================================
# STAGE 4 — APPLY (OPTIONAL)
# ======================================================
- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Approval
  jobs:
    - job: TerraformApply
      displayName: "Terraform Apply Execution"
      condition: eq(${{ parameters.apply}}, 'true')
      steps:

        - task: TerraformTask@5
          inputs:
            provider: azurerm
            command: init
            workingDirectory: '$(work_dir)'
            backendServiceArm: '$(service_connection)'
            backendAzureRmStorageAccountName: '$(stg_account_name)'
            backendAzureRmContainerName: tfstate
            backendAzureRmKey: '$(backendAzureRmKey)'

        - task: TerraformTask@5
          inputs:
            provider: azurerm
            command: apply
            workingDirectory: '$(work_dir)'
            environmentServiceNameAzureRM: '$(service_connection)'
